export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LIST_CATEGORY_REQUEST = 'PRODUCT_LIST_CATEGORY_REQUEST'
export const PRODUCT_LIST_CATEGORY_SUCCESS = 'PRODUCT_LIST_CATEGORY_SUCCESS'
export const PRODUCT_LIST_CATEGORY_FAIL = 'PRODUCT_LIST_CATEGORY_FAIL'

export const PRODUCT_LIST_SUGGESTION_REQUEST = 'PRODUCT_LIST_SUGGESTION_REQUEST'
export const PRODUCT_LIST_SUGGESTION_SUCCESS = 'PRODUCT_LIST_SUGGESTION_SUCCESS'
export const PRODUCT_LIST_SUGGESTION_FAIL = 'PRODUCT_LIST_SUGGESTION_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET'

export const PRODUCT_TOP_RATED_REQUEST = 'PRODUCT_TOP_RATED_REQUEST'
export const PRODUCT_TOP_RATED_SUCCESS = 'PRODUCT_TOP_RATED_SUCCESS'
export const PRODUCT_TOP_RATED_FAIL = 'PRODUCT_TOP_RATED_FAIL'

export const PRODUCT_BEST_REQUEST = 'PRODUCT_BEST_REQUEST'
export const PRODUCT_BEST_SUCCESS = 'PRODUCT_BEST_SUCCESS'
export const PRODUCT_BEST_FAIL = 'PRODUCT_BEST_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'